name: freezed_lint
version: 0.2.30
description: Flutter freezed convention linter (custom_lint plugin).

publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  analyzer: ^8.0.0
  custom_lint_builder: ^0.8.1
