name: architecture_lint_analyzer_plugin
version: 0.2.21
description: Analyzer plugin entry point for architecture_lint.

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  architecture_lint:
    git:
      url: https://github.com/JosephNK/jkit-code-plugin.git
      path: rules/flutter/base/custom-lint/architecture_lint
      ref: v0.2.21
  analyzer: ">=6.0.0 <13.0.0"
  analyzer_plugin: ">=0.13.0 <0.15.0"

dev_dependencies:
  lints: ^5.0.0
