// Commit message linter config for downstream projects.
// Generated by scripts/gen-commitlint.mjs from rules/common/commitlint.config.mjs.
//
// Allowed types mirror rules/common/git.md. Update the source file and
// re-run gen-commitlint.mjs; do not edit the generated copy.
export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      ['feat', 'fix', 'refactor', 'docs', 'test', 'chore', 'perf', 'ci'],
    ],
  },
};
