name: architecture_lint
version: 0.2.3
description: Flutter hexagonal architecture linter plugin (analyzer + analyzer_plugin).

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

executables:
  architecture_lint: lint

dependencies:
  analyzer: ">=6.0.0 <13.0.0"
  analyzer_plugin: ">=0.13.0 <0.15.0"
  glob: ^2.1.0
  path: ^1.0.0
